branch: main
download-external-modules: false
framework:
  - terraform
  - kubernetes
  - dockerfile
soft-fail: true
skip-check:
  - CKV_AZURE_12    # Storage account secure transfer
  - CKV_AZURE_34    # Blob container public access
  - CKV_K8S_11      # CPU limits
  - CKV_DOCKER_3    # Non-root user
  - CKV_DOCKER_7    # Latest tag
  - CKV_GITHUB_6    # GitHub 2FA
quiet: true
output: sarif