apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinion-weather-api
  namespace: infinion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinion-weather-api
  template:
    metadata:
      labels:
        app: infinion-weather-api
    spec:
      containers:
      - name: infinion-weather-api
        image: infinionacr1760906713.azurecr.io/infinion-weather-api:latest
        ports:
        - containerPort: 8080  
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://*:8080"  
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080  
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080  
          initialDelaySeconds: 30
          periodSeconds: 20
